name: CI-CD Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Docker Image
        run: |
          docker build -t a880/devops-cicd-backend:latest ./backend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push a880/devops-cicd-backend:latest

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull a880/devops-cicd-backend:latest
            sudo docker stop django-app || true
            sudo docker rm django-app || true
            sudo docker run -d --name django-app -p 80:8000 a880/devops-cicd-backend:latest
